//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادرس کیف پول.
        /// </summary>
        public static string AccountAddress {
            get {
                return ResourceManager.GetString("AccountAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کیف پول.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال سازی.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش شماره بانک.
        /// </summary>
        public static string BankPreNumber {
            get {
                return ResourceManager.GetString("BankPreNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضای کد فعال سازی.
        /// </summary>
        public static string ExpireTimeActivationCode {
            get {
                return ResourceManager.GetString("ExpireTimeActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانم.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 639599.
        /// </summary>
        public static string GhavaminBank {
            get {
                return ResourceManager.GetString("GhavaminBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سکه طلا.
        /// </summary>
        public static string GoldenCoin {
            get {
                return ResourceManager.GetString("GoldenCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور هش شده.
        /// </summary>
        public static string HashedPassword {
            get {
                return ResourceManager.GetString("HashedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایران.
        /// </summary>
        public static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603770.
        /// </summary>
        public static string KeshavarziBank {
            get {
                return ResourceManager.GetString("KeshavarziBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آقا.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 628023.
        /// </summary>
        public static string MaskanBank {
            get {
                return ResourceManager.GetString("MaskanBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 639370.
        /// </summary>
        public static string MehrEghtesadBank {
            get {
                return ResourceManager.GetString("MehrEghtesadBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 610433.
        /// </summary>
        public static string MellatBank {
            get {
                return ResourceManager.GetString("MellatBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603799.
        /// </summary>
        public static string MelliBank {
            get {
                return ResourceManager.GetString("MelliBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک نور.
        /// </summary>
        public static string NoorBank {
            get {
                return ResourceManager.GetString("NoorBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 622106.
        /// </summary>
        public static string ParsianBank {
            get {
                return ResourceManager.GetString("ParsianBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 502229.
        /// </summary>
        public static string PasargadBank {
            get {
                return ResourceManager.GetString("PasargadBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 589463.
        /// </summary>
        public static string RefahBank {
            get {
                return ResourceManager.GetString("RefahBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ریال.
        /// </summary>
        public static string Rial {
            get {
                return ResourceManager.GetString("Rial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 603769.
        /// </summary>
        public static string SaderatBank {
            get {
                return ResourceManager.GetString("SaderatBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 621986.
        /// </summary>
        public static string SamanBank {
            get {
                return ResourceManager.GetString("SamanBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 627961.
        /// </summary>
        public static string SanatMadanBank {
            get {
                return ResourceManager.GetString("SanatMadanBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 639607.
        /// </summary>
        public static string SarmayehBank {
            get {
                return ResourceManager.GetString("SarmayehBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 589210.
        /// </summary>
        public static string SepahBank {
            get {
                return ResourceManager.GetString("SepahBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 502806.
        /// </summary>
        public static string ShahrBank {
            get {
                return ResourceManager.GetString("ShahrBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سکه نقره.
        /// </summary>
        public static string SilverCoin {
            get {
                return ResourceManager.GetString("SilverCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر کل.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 627353.
        /// </summary>
        public static string TejaratBank {
            get {
                return ResourceManager.GetString("TejaratBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
